### ISSUE TITLE
三通道图像作为输出

### ISSUE THREAD

**Issue by yaoliu0803** [tthinking/MATR#10]
作者您好，我参考了DPCN_fusion这篇论文的代码去处理RGB类型的图像，先将RGB色彩空间转换为YUV，把Y通道作为模型的输入，得到的结果在融合UV通道。但是在使用yuv2rgb()方法时出现了警告提示：Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning。另外，融合出来的结果效果并不好，请问是什么原因？
![image](https://github.com/tthinking/MATR/assets/103411296/b6b93a03-3437-4d57-9506-97c60b35e8a3)

**Comment by tthinking** [comment]
Section IV-A.
all of these samples are normalized to [0, 1].

**Comment by yaoliu0803** [comment]
作者您给的RGB图像参考链接(https://github.com/tthinking/DPCN-Fusion/tree/master)是按如下方式处理图片，它是将图像归一化到[-1,1]
![image](https://github.com/tthinking/MATR/assets/103411296/65be999d-bdff-4667-8146-cbb55bfe4cac)

请问作者能否提供相应归一化到[0，1]的代码供参考呢？
