### ISSUE TITLE
关于训练代码

### ISSUE THREAD

**Issue by wangsh7** [tthinking/MATR#8]
请问您有用于彩色图像融合适用的训练代码么，PET-MRI或者SPECT—MRI的，求回答，谢谢

**Comment by tthinking** [comment]
<strong>Dealing with RGB input:</strong> Refer to [DPCN-Fusion](https://github.com/tthinking/DPCN-Fusion/blob/master).

**Comment by Zss8796** [comment]
> 请问您有用于彩色图像融合适用的训练代码么，PET-MRI或者SPECT—MRI的，求回答，谢谢

请问您的训练代码调配好了吗？如果是的话方便分享一下吗 谢谢。
