### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by songwenhao123** [tthinking/MATR#9]
作者您好，请问客观数据代码如何运行？十分感谢！

**Comment by tthinking** [comment]
The code for <strong>evaluation metrics</strong> is [here](https://github.com/tthinking/MATR/tree/main/evaluation).

**Comment by songwenhao123** [comment]
> The code for **evaluation metrics** is [here](https://github.com/tthinking/MATR/tree/main/evaluation).

好的，非常感谢您的回复！！！

**Comment by moon-yu** [comment]
你好请问这个.m文件是可以在这个项目下面直接运行还是要去matlab里面呢？那么我应该如何调用运行呢？如有回复感激不尽谢谢
